[[redirects]]
  from = "https://aquarium-sim-2022.netlify.app"
  to = "https://https://mysql-aquarium.herokuapp.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200