[[redirects]]
  from = "https://624e6bcf69b4ed00097d2ed9--eclectic-blini-3e80af.netlify.app/compendium"
  to = "https://https://mysql-aquarium.herokuapp.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200